name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "35.219.50.99"
UUID = "0a0b2275-7900-4303-bc50-5c6bd8db199b"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
